### ISSUE TITLE
BehaviorSubject: Only one thread can await a Resumable

### ISSUE THREAD

**Issue by rougsig** [akarnokd/kotlin-flow-extensions#33]
I think there is only one thread. Why i got that exception?

```kotlin
@Test
fun singleThread() {
  runBlocking {
    val subject = BehaviorSubject(0)
    async {
      subject.collect {
        println("collect $it")
      }
    }

    (1..9).map {
      async {
        subject.emit(it)
        println("send $it")
      }
    }
  }
}
```
```log
java.lang.IllegalStateException: Only one thread can await a Resumable

	at hu.akarnokd.kotlin.flow.Resumable.await(Resumable.kt:51)
	at hu.akarnokd.kotlin.flow.BehaviorSubject.emit(BehaviorSubject.kt:103)
	at com.github.rougsig.Test$a$1$invokeSuspend$$inlined$map$lambda$1.invokeSuspend(Test.kt:148)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by akarnokd** [comment]
Isn't 

```kotlin
async {
        subject.emit(it)
        println("send $it")
}
```

starting individual tasks for that 1..9 loop?

**Comment by rougsig** [comment]
Yes. It is. 
But it is same thread, not another.

**Comment by akarnokd** [comment]
Maybe the carrier thread is the same, but when the first `async { }` suspends, the second one starts running and tries to interact with the `BehaviorSubject` again, which is a reentrant usage and thus fails the assertion.

**Comment by rougsig** [comment]
So i must use ony one coroutine to emit items to `BehaviorSubject`? If its true, i think its misleading exception naming, maybe that can be better `Only one coroutine can await a Resumable`
Like that? (it is working, without exceptions)

```kotlin
@Test
fun singleThread() {
  runBlocking {
    val queue = Channel<Int>(Channel.UNLIMITED)
    val subject = BehaviorSubject(0)

    launch {
      for (i in queue) {
        subject.emit(i)
      }
    }

    async {
      subject.collect {
        println("collect $it")
      }
    }

    (1..9).map {
      async {
        queue.send(it)
        println("send $it")
      }
    }
  }
}
```

**Comment by akarnokd** [comment]
Yeah, probably.

**Comment by rougsig** [comment]
Thank you.
